### ISSUE TITLE
Kodi crashes/closes with any addon, Manjaro KDE.

### ISSUE THREAD

**Issue by JackDinn** [xbmc/xbmc#21370]
I have tried kodi 19.4 on Linux (Manjaro KDE) from the community repo and iv also tried manually building latest build from git kodi 20-alpha1.
Kodi seems fine until i install any addon and then try to use it, kodi just crashes/closes with all of the addons i have tested.

I suspect its a python problem.
```
System:
  Host: greg-inspiron5767 Kernel: 5.15.32-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.4 Distro: Manjaro Linux
Machine:
  Type: Laptop System: Dell product: Inspiron 5767 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 03XWWJ v: A00 serial: <superuser required>
    UEFI-[Legacy]: Dell v: 1.4.1 date: 12/24/2020

kodi 19.4 (Also tried Kodi 20-alpha)
Python 3.10.4
```
Logs https://pastebin.com/0iZYK3qY
